<script setup lang="ts">
import { useAuthStore } from '@/stores/auth'

const auth = useAuthStore()
</script>
<template>
  <div class="landing">
    <header><router-link to="/" class="brand"><span>✚</span>Manta Cuida IA</router-link><nav><router-link v-if="!auth.isAuthenticated" to="/login">Ingresar</router-link><router-link v-if="!auth.isAuthenticated" to="/registro" class="btn btn-primary">Crear cuenta</router-link><router-link v-else to="/app" class="btn btn-primary">Abrir aplicación</router-link></nav></header>
    <main class="hero"><section><div class="pill">🌊 Impacto local · Manta, Ecuador</div><h1>Orientación inteligente para acceder al <em>servicio de salud adecuado</em>.</h1><p>Un sistema multiagente con GPT-5.6 y n8n que clasifica necesidades, detecta señales de alerta, consulta servicios y genera seguimiento trazable.</p><div class="actions"><router-link :to="auth.isAuthenticated?'/app/chat':'/login'" class="btn btn-primary">Comenzar orientación</router-link><a href="#funciones" class="btn btn-secondary">Ver cómo funciona</a></div><div class="notice"><strong>Importante:</strong> no diagnostica ni sustituye a profesionales. Ante una emergencia llama al ECU 911.</div></section><aside><div class="phone"><div class="phone-head"><span>✚</span><div><strong>Manta Cuida IA</strong><small>Asistente activo · GPT-5.6</small></div></div><div class="bubble user">Mi mamá tiene dificultad para respirar.</div><div class="alert">🔴 Posible situación urgente</div><div class="bubble ai">Busca atención inmediata y pide a una persona que te acompañe. ¿Está consciente y acompañada?</div><div class="status">✓ Caso registrado · Revisión humana solicitada</div></div></aside></main>
    <section id="funciones" class="features"><article><span>🧠</span><h3>Clasificación segura</h3><p>GPT-5.6 estructura el caso y reglas independientes evitan reducir una alerta crítica.</p></article><article><span>📍</span><h3>Acceso a servicios</h3><p>Busca por tipo de atención, sector, requisitos y características de accesibilidad.</p></article><article><span>🔁</span><h3>Seguimiento real</h3><p>n8n registra el caso, genera acciones y permite revisión por operadores.</p></article></section>
    <footer>Proyecto de buildathon · Salud y acceso a servicios · Manta Cuida IA</footer>
  </div>
</template>
<style scoped>.landing{min-height:100vh;background:radial-gradient(circle at 80% 10%,#cffafe 0,transparent 30%),#f8fafc}header{height:74px;display:flex;align-items:center;justify-content:space-between;max-width:1180px;margin:auto;padding:0 1.25rem}.brand{display:flex;gap:.55rem;align-items:center;color:#082f49;font-weight:900;font-size:1.15rem;text-decoration:none}.brand span{width:34px;height:34px;border-radius:9px;background:#0e7490;color:#fff;display:grid;place-items:center}nav{display:flex;gap:.7rem;align-items:center}.hero{max-width:1180px;margin:auto;min-height:630px;display:grid;grid-template-columns:1.1fr .9fr;gap:3rem;align-items:center;padding:3rem 1.25rem}.pill{display:inline-flex;background:#ecfeff;color:#155e75;padding:.4rem .75rem;border-radius:999px;font-size:.78rem;font-weight:800}.hero h1{font-size:clamp(2.4rem,5vw,4.6rem);line-height:1.02;color:#082f49;margin:1rem 0}.hero h1 em{font-style:normal;color:#0e7490}.hero section>p{font-size:1.1rem;color:#475569;max-width:650px}.actions{display:flex;gap:.8rem;margin:1.5rem 0}.notice{font-size:.8rem;color:#64748b;max-width:610px}.phone{max-width:390px;margin:auto;background:#fff;border:10px solid #082f49;border-radius:34px;padding:1rem;box-shadow:0 30px 70px rgba(8,47,73,.2)}.phone-head{display:flex;gap:.6rem;align-items:center;border-bottom:1px solid #e2e8f0;padding-bottom:.8rem}.phone-head>span{width:34px;height:34px;background:#2dd4bf;border-radius:9px;display:grid;place-items:center}.phone-head div{display:flex;flex-direction:column}.phone-head small{color:#64748b}.bubble{padding:.7rem .85rem;border-radius:12px;margin:.85rem 0;font-size:.82rem}.user{background:#082f49;color:#fff;margin-left:18%}.ai{background:#f1f5f9;margin-right:8%}.alert{background:#fee2e2;color:#991b1b;padding:.65rem;border-radius:9px;font-weight:800;font-size:.78rem}.status{font-size:.7rem;color:#0f766e;background:#ccfbf1;padding:.55rem;border-radius:8px}.features{max-width:1100px;margin:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;padding:2rem 1.25rem 5rem}.features article{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:1.4rem}.features span{font-size:1.8rem}.features h3{color:#082f49;margin:.5rem 0}.features p{font-size:.9rem;color:#64748b}footer{text-align:center;padding:1.5rem;color:#64748b;border-top:1px solid #e2e8f0}@media(max-width:800px){.hero{grid-template-columns:1fr;padding-top:2rem}.hero aside{order:-1}.features{grid-template-columns:1fr}nav>a:not(.btn){display:none}}
</style>
